---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
  - name: debian-7.4
    run_list:
      - recipe[apt]
  - name: centos-6.4

suites:
- name: git
  run_list:
  - recipe[minitest-handler]
  - recipe[diamond_test::git]
  - recipe[diamond_test::processcollector]
  attributes: {}
- name: tarball
  run_list:
  - recipe[minitest-handler]
  - recipe[diamond_test::tarball]
  - recipe[diamond_test::processcollector]
  attributes: {}
